Sensitivity analysis methods
aimclub/GEFEST pull request #51
Opened 2022-11-07 17:02 UTC by DenisSidoren

2023-07-18 18:09 UTC, MangaBoba commented on gefest/core/algs/sensetivity/sa_core.py
> +            non_unvalid = not any(
Возможно опечатка.

2023-07-18 18:42 UTC, MangaBoba commented on gefest/core/algs/sensetivity/draft_sa_testing.ipynb
Ноутбуки считаю не лучшим артефактом для гита. Но если добавлять, то наверное лучше в папку с примерами cases, а не в ядро.

2023-07-27 22:35 UTC, maypink requested changes

2023-07-27 22:35 UTC, maypink commented on gefest/core/algs/sensetivity/draft_sa.py
> +                while step_fitnes <= current_fitnes and max_attempts > 0:
я правильно понимаю, что все это будет продолжаться, пока фитнесс будет улучшаться на более, чем на единицу в третьем знаке? кажется, что вероятность почти навсегда застрять достаточно высока, хотелось бы иметь максимальное кол-во итераций на такой случай, например 10

2023-07-27 22:35 UTC, maypink commented on gefest/core/algs/sensetivity/draft_sa.py
> +class SA_methods:
_SensitivityAnalysisMethods_

2023-07-27 22:35 UTC, maypink commented on gefest/core/algs/sensetivity/draft_sa.py
> +                length_strcuture.append(sum(length_polygons))
_length_structure_, опечатка

2023-07-27 22:35 UTC, maypink commented on gefest/core/algs/sensetivity/draft_sa.py
> +                    fitnes_diff = round(
а почему фитнес округляется до 3 знака, а разница до 1?

2023-07-27 22:35 UTC, maypink commented on gefest/core/algs/sensetivity/draft_sa.py
> +        super().__init__()
если ничего нового не прокидывается в дочернем классе, можно не писать __init__

2023-07-27 22:36 UTC, maypink commented on cases/sensitivity_analysis/configuration_sa/sa_domain.py
> +grid_resolution_x = 83  # Number of points on x-axis
если это константы, то капсом

2023-07-27 22:37 UTC, maypink commented on cases/sensitivity_analysis/configuration_sa/sa_estimator.py
> +def configurate_estimator(domain, path_sim=False):
надо бы типов добавить везде

2023-07-27 22:40 UTC, maypink commented on gefest/core/opt/operators/sensitivity_methods.py
> +geometry = Geometry2D()
выглядит странно, нельзя ли в функциях ниже просто вызывать каждый раз Geometry2D()? там же всего 2 раза это делается

2023-08-27 07:06 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
это черновик был, файл удален

2023-08-27 07:06 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa_testing.ipynb
это черновик был, файл удален

2023-08-27 07:06 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +import itertools
исправлено

2023-08-27 07:08 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +        current_fitnes = init_fitnes
done

2023-08-27 07:09 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +                while step_fitnes <= current_fitnes and max_attempts > 0:
это черновик был, файл удален

2023-08-27 07:19 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +class SA_methods:
done

2023-08-27 07:20 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +                length_strcuture.append(sum(length_polygons))
удалена вместе с файлом

2023-08-27 07:20 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +        super().__init__()
удален вместе с файлом

2023-08-27 07:23 UTC, DenisSidoren commented on cases/sensitivity_analysis/configuration_sa/sa_domain.py
> +grid_resolution_x = 83  # Number of points on x-axis
да, но тогда во всем проекте надо это исправлять

2023-08-27 07:24 UTC, DenisSidoren commented on cases/sensitivity_analysis/configuration_sa/sa_estimator.py
> +def configurate_estimator(domain, path_sim=False):
согласен, можно будет это сделать в дальнейших итерациях по причесыванию проекта

2023-08-27 07:29 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/sa_core.py
> +            non_unvalid = not any(
исправлено

2023-08-27 07:29 UTC, DenisSidoren commented on optimized.pkl
файл удален

2023-08-27 07:30 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +                    fitnes_diff = round(
на самом деле можно всё округлять до 1 знака

2023-08-27 07:35 UTC, DenisSidoren commented on gefest/core/algs/sensetivity/draft_sa.py
> +                while step_fitnes <= current_fitnes and max_attempts > 0:
однако логика такая да. звучит странно, но на практике алгоритм не застревает никогда потому, что шаг смещения достаточно велик для того, чтобы изменения были закономерно в третьем знаке. Плюс внутри области поиска решения с малой вероятностью существует какая-то обширная "область наилучшего положения объекта", внутри которой перемещение объекта не изменяется. фитнес всё-таки или улучшается или ухудшается от перемещения

2023-08-27 07:40 UTC, DenisSidoren commented on gefest/core/opt/operators/sensitivity_methods.py
> +geometry = Geometry2D()
мне кажется выглядит нормально

2023-09-01 16:33 UTC, MangaBoba approved these changes

2023-09-01 19:05 UTC, nicl-nno approved these changes

2023-09-02 15:45 UTC, merged