MO algorithms realization
aimclub/GEFEST pull request #52
Opened 2022-12-23 14:25 UTC by quickjkee

2022-12-23 15:50 UTC, nicl-nno requested changes

2022-12-23 15:50 UTC, nicl-nno commented on gefest/tools/optimizers/fedot_optimizer/nsga2.py
> +from fedot.core.optimisers.gp_comp.gp_optimizer import EvoGraphOptimizer
Видимо нужно добавить FEDOT в зависимости? И указать версию.

2022-12-23 15:50 UTC, nicl-nno commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        r = W.shape[0]
Кое-где pep8 нарушен.

2022-12-23 15:50 UTC, nicl-nno commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        self.crossover_rate = crossover_rate
Большая часть кода повторяется. Может, её вынести в базовый класс (имеющийся или промежуточный)?

2022-12-23 15:50 UTC, nicl-nno commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        self.initial_graphs = self._pop
Аналогично про повтор.

2022-12-23 15:50 UTC, nicl-nno commented on cases/synthetic/multiobj/configuration/multiobj_estimator.py
> +    def len_num_ration(struct: Structure):
ratio, видимо.

2022-12-23 15:50 UTC, nicl-nno commented on cases/synthetic/multiobj/configuration/multiobj_optimizer.py
> +              'initial_graphs': [1, 2, 3]}
А что такое [1, 2, 3]?

2022-12-30 01:56 UTC, quickjkee commented on gefest/tools/optimizers/fedot_optimizer/nsga2.py
> +from fedot.core.optimisers.gp_comp.gp_optimizer import EvoGraphOptimizer
добавил

2022-12-30 01:57 UTC, quickjkee commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        r = W.shape[0]
подправил

2022-12-30 01:57 UTC, quickjkee commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        self.crossover_rate = crossover_rate
убрал большую часть в базовый класс

2022-12-30 01:57 UTC, quickjkee commented on gefest/tools/optimizers/fedot_optimizer/age.py
> +        self.initial_graphs = self._pop
эту часть убрал

2022-12-30 01:57 UTC, quickjkee commented on cases/synthetic/multiobj/configuration/multiobj_estimator.py
> +    def len_num_ration(struct: Structure):
исправил

2022-12-30 01:57 UTC, quickjkee commented on cases/synthetic/multiobj/configuration/multiobj_optimizer.py
> +              'initial_graphs': [1, 2, 3]}
просит начальный граф на вход, подаю что-то рандомное

2022-12-30 08:49 UTC, nicl-nno commented on cases/synthetic/multiobj/configuration/multiobj_optimizer.py
> +              'initial_graphs': [1, 2, 3]}
А у вершин графа не должно быть по две координаты?

2022-12-30 09:28 UTC, nicl-nno approved these changes

2022-12-30 09:29 UTC, nicl-nno commented
Надо только версию pytest ещё поправить, чтобы тесты проходили.

2023-01-11 20:53 UTC, quickjkee commented on cases/synthetic/multiobj/configuration/multiobj_optimizer.py
> +              'initial_graphs': [1, 2, 3]}
должно быть, это рандомный инит, он потом заменяется на нормальные графы

2023-01-11 20:54 UTC, quickjkee commented
вроде здесь у pytest такая же версия как в мейне

2023-01-22 10:41 UTC, nicl-nno commented
>вроде здесь у pytest такая же версия как в мейне

Да, но тут добавлен fedot, у которого она другая (0.6.2). Это вот тут видно https://github.com/aimclub/GEFEST/actions/runs/3905783442/jobs/6673202650

2023-01-31 19:01 UTC, merged